`timescale 1ns / 1ps
//
// accel_spi.v
//
// SPI master for the Nexys A7 on-board ADXL362 3-axis accelerometer.
// Puts the ADXL362 into measurement mode, then continuously reads the
// 8-bit signed XDATA register (~1 kHz rate).
//
// Protocol: SPI Mode 0 (CPOL=0, CPHA=0), MSB-first, 24-bit transactions.
//   Write: [0x0A][addr][data]
//   Read:  [0x0B][addr][0x00]  -- MISO byte 2 = register value
//
// ADXL362 key registers:
//   0x2D POWER_CTL  : write 0x02 to enter Measurement mode
//   0x08 XDATA      : 8-bit signed X acceleration (±2 g default)
//

module accel_spi(
    input  wire       clk,        // 100 MHz system clock
    input  wire       rst,        // synchronous reset (active high)

    // SPI pins (connect directly to top-level ports)
    output reg        acl_csn,    // chip-select, active LOW
    output reg        acl_sclk,   // SPI clock (~1 MHz)
    output reg        acl_mosi,   // master → slave
    input  wire       acl_miso,   // slave  → master

    // Decoded output
    output reg [7:0]  x_data,     // signed 8-bit X acceleration (updates ~1 kHz)
    output reg        data_valid  // pulses HIGH for one clk cycle when x_data is fresh
);

    // ---------------------------------------------------------------
    // Timing constants (all referenced to 100 MHz system clock)
    // ---------------------------------------------------------------
    // SPI clock = 100 MHz / (2 × HALF_PER) = 1 MHz
    localparam HALF_PER     = 7'd50;
    // Power-on wait ≈ 10 ms
    localparam POWERON_WAIT = 20'd1_000_000;
    // Gap after config write: must be ≥ 1 ODR period (10 ms at 100 Hz default)
    localparam CFG_GAP      = 20'd1_000_000;
    // Delay between successive X reads ≈ 1 ms
    localparam READ_DELAY   = 17'd100_000;

    // ---------------------------------------------------------------
    // State encoding
    // ---------------------------------------------------------------
    localparam [2:0]
        S_POWERON  = 3'd0,   // wait for ADXL362 power-on
        S_CFG      = 3'd1,   // SPI write: POWER_CTL = 0x02
        S_CFG_DONE = 3'd2,   // short pause after config
        S_READ     = 3'd3,   // SPI read: XDATA register
        S_DELAY    = 3'd4;   // inter-read pause

    reg [2:0]  state;

    // General-purpose delay counter (covers the largest delay, POWERON_WAIT)
    reg [19:0] long_cnt;

    // SPI engine registers
    reg [6:0]  half_cnt;    // half-period divider (0 .. HALF_PER-1)
    reg [4:0]  bit_cnt;     // bit index within 24-bit transaction (0 .. 23)
    reg [23:0] tx_reg;      // TX shift register
    reg [23:0] rx_reg;      // RX shift register (received MSB → bit[23])
    reg        done_flag;   // set on the rising edge that clocks the last bit

    // ---------------------------------------------------------------
    // Helper: begin a new SPI transaction.
    // Because non-blocking assignments in the same always block are fine,
    // we inline the setup at every state transition.
    // ---------------------------------------------------------------

    always @(posedge clk or posedge rst) begin
        if (rst) begin
            state      <= S_POWERON;
            long_cnt   <= 20'd0;
            half_cnt   <= 7'd0;
            bit_cnt    <= 5'd0;
            tx_reg     <= 24'd0;
            rx_reg     <= 24'd0;
            done_flag  <= 1'b0;
            acl_csn    <= 1'b1;
            acl_sclk   <= 1'b0;
            acl_mosi   <= 1'b0;
            x_data     <= 8'h00;
            data_valid <= 1'b0;
        end else begin
            // Default: clear pulse
            data_valid <= 1'b0;

            case (state)

                // ---------------------------------------------------
                // Wait ~10 ms for the ADXL362 to boot after power-on
                // ---------------------------------------------------
                S_POWERON: begin
                    if (long_cnt == POWERON_WAIT - 1) begin
                        long_cnt  <= 20'd0;
                        // Begin SPI write: POWER_CTL (0x2D) ← 0x02
                        // 0x0A_2D_02 → bit[23]=0, set MOSI=0 before first edge
                        tx_reg    <= 24'h0A_2D_02;
                        acl_csn   <= 1'b0;
                        acl_sclk  <= 1'b0;
                        acl_mosi  <= 1'b0;   // MSB of 0x0A is 0
                        half_cnt  <= 7'd0;
                        bit_cnt   <= 5'd0;
                        done_flag <= 1'b0;
                        state     <= S_CFG;
                    end else
                        long_cnt <= long_cnt + 20'd1;
                end

                // ---------------------------------------------------
                // SPI transaction engine (shared by S_CFG and S_READ)
                //
                // SCLK is generated by toggling on half_cnt overflow.
                // We check acl_sclk's CURRENT (pre-toggle) value to
                // detect rising vs falling edges -- NBAs guarantee the
                // check reads the old register value.
                // ---------------------------------------------------
                S_CFG,
                S_READ: begin
                    if (half_cnt < HALF_PER - 1) begin
                        half_cnt <= half_cnt + 7'd1;
                    end else begin
                        // Half-period elapsed: toggle SCLK
                        half_cnt <= 7'd0;
                        acl_sclk <= ~acl_sclk;

                        if (acl_sclk == 1'b0) begin
                            // ---- RISING EDGE: shift MISO into rx_reg ----
                            rx_reg <= {rx_reg[22:0], acl_miso};
                            if (bit_cnt == 5'd23)
                                done_flag <= 1'b1;   // all 24 bits captured

                        end else begin
                            // ---- FALLING EDGE ----
                            if (!done_flag) begin
                                // Shift TX left and present next MOSI bit
                                tx_reg   <= {tx_reg[22:0], 1'b0};
                                acl_mosi <= tx_reg[22]; // old bit[22] = next to send
                                bit_cnt  <= bit_cnt + 5'd1;
                            end else begin
                                // Transaction complete: deassert CS
                                acl_csn  <= 1'b1;
                                acl_mosi <= 1'b0;
                                long_cnt <= 20'd0;
                                if (state == S_CFG)
                                    state <= S_CFG_DONE;
                                else begin
                                    // Capture received XDATA from last byte
                                    x_data     <= rx_reg[7:0];
                                    data_valid <= 1'b1;
                                    state      <= S_DELAY;
                                end
                            end
                        end
                    end
                end

                // ---------------------------------------------------
                // Short gap after config, then start reading
                // ---------------------------------------------------
                S_CFG_DONE: begin
                    if (long_cnt == CFG_GAP - 1) begin
                        long_cnt  <= 20'd0;
                        // Begin SPI read: XDATA (0x08)
                        // 0x0B_08_00 → bit[23]=0
                        tx_reg    <= 24'h0B_08_00;
                        acl_csn   <= 1'b0;
                        acl_sclk  <= 1'b0;
                        acl_mosi  <= 1'b0;   // MSB of 0x0B is 0
                        half_cnt  <= 7'd0;
                        bit_cnt   <= 5'd0;
                        done_flag <= 1'b0;
                        state     <= S_READ;
                    end else
                        long_cnt <= long_cnt + 20'd1;
                end

                // ---------------------------------------------------
                // ~1 ms pause between consecutive X reads
                // ---------------------------------------------------
                S_DELAY: begin
                    if (long_cnt == READ_DELAY - 1) begin
                        long_cnt  <= 20'd0;
                        tx_reg    <= 24'h0B_08_00;
                        acl_csn   <= 1'b0;
                        acl_sclk  <= 1'b0;
                        acl_mosi  <= 1'b0;
                        half_cnt  <= 7'd0;
                        bit_cnt   <= 5'd0;
                        done_flag <= 1'b0;
                        state     <= S_READ;
                    end else
                        long_cnt <= long_cnt + 20'd1;
                end

                default: state <= S_POWERON;
            endcase
        end
    end

endmodule
